# Check out the repo, setup JDK and run Maven tests.
name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master, develop ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, macOS-latest, ubuntu-latest ]
        jdk: [ 17 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'

      - name: Test with Maven
        run: |
          ./mvnw --quiet --batch-mode test
